apiVersion: v1
kind: Secret

metadata:
  name: ai-platform-secret
  namespace: ai-task-platform

type: Opaque

stringData:

  JWT_SECRET: your-super-secret-key

  MONGO_URI: mongodb+srv://hellonitin199_db_user:dDP9W8plSsR1Pajr@cluster0.jhczs9n.mongodb.net/ai-task-platform?retryWrites=true&w=majority&appName=Cluster0